// Code generated by cmd/epsg-gen. DO NOT EDIT.
//
// Data sourced from the EPSG Geodetic Parameter Dataset.
// Copyright © IOGP. All rights reserved. See https://epsg.org/terms-of-use.html

package core

// epsgDimTable maps EPSG code to the number of spatial dimensions defined by that CRS.
var epsgDimTable = map[int]uint{
	4326: 2, // WGS 84
	4612: 2, // JGD2000
	6668: 2, // JGD2011
}
