package internal

// GML element local names used in switch statements and handler maps.
const (
	gmlPoint                  = "Point"
	gmlLineString             = "LineString"
	gmlPolygon                = "Polygon"
	gmlCurve                  = "Curve"
	gmlSurface                = "Surface"
	gmlOrientableCurve        = "OrientableCurve"
	gmlOrientableSurface      = "OrientableSurface"
	gmlCompositeCurve         = "CompositeCurve"
	gmlCompositeSurface       = "CompositeSurface"
	gmlMultiPoint             = "MultiPoint"
	gmlMultiCurve             = "MultiCurve"
	gmlMultiLineString        = "MultiLineString"
	gmlMultiSurface           = "MultiSurface"
	gmlMultiPolygon           = "MultiPolygon"
	gmlEnvelope               = "Envelope"
	gmlGrid                   = "Grid"
	gmlRectifiedGrid          = "RectifiedGrid"
	gmlSolid                  = "Solid"
	gmlCompositeSolid         = "CompositeSolid"
	gmlMultiSolid             = "MultiSolid"
	gmlTin                    = "Tin"
	gmlTriangulatedSurface    = "TriangulatedSurface"
	gmlPolyhedralSurface      = "PolyhedralSurface"
	gmlShell                  = "Shell"
	gmlBoundedBy              = "boundedBy"
	gmlEnvelopeWithTimePeriod = "EnvelopeWithTimePeriod"
	gmlDomainSet              = "domainSet"
	gmlRangeSet               = "rangeSet"
)
