package xsdlite

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// Generate produces a Go source file string for the given types.
// withDoc controls whether XSD documentation is emitted as field comments.
// mapNS maps namespace URI → Go package import path. Types from those
// namespaces are not generated as structs (they come from the external package),
// but fields referencing them are kept and their Go type is qualified with the
// derived package alias.
// xsdSource is the input XSD file path (used in the generated-file header).
// version is the tool version string (used in the generated-file header).
func Generate(types []*ComplexType, pkgName string, skipAbstract bool, withDoc bool, mapNS map[string]string, xsdSource string, version string) (string, error) {
	// Build ns→alias and alias→pkgPath tables, checking for alias collisions.
	aliases := make(map[string]string)     // ns → alias
	importPaths := make(map[string]string) // alias → pkgPath
	aliasToNS := make(map[string]string)   // alias → first ns (collision detection)
	for ns, pkgPath := range mapNS {
		alias := deriveAlias(pkgPath)
		if prevNS, exists := aliasToNS[alias]; exists && prevNS != ns {
			return "", fmt.Errorf("alias collision: namespaces %q and %q both derive alias %q; use different package paths", prevNS, ns, alias)
		}
		aliases[ns] = alias
		importPaths[alias] = pkgPath
		aliasToNS[alias] = ns
	}

	// Sort for deterministic output.
	sort.Slice(types, func(i, j int) bool {
		return types[i].Name < types[j].Name
	})

	usedAliases := make(map[string]bool)
	var structsSB strings.Builder
	for _, ct := range types {
		if skipAbstract && ct.Abstract {
			continue
		}
		if ct.Name == "" {
			continue
		}
		writeStruct(&structsSB, ct, withDoc, aliases, usedAliases)
	}

	var header strings.Builder

	// Generated-file header (only when at least one of version/xsdSource is set).
	if version != "" || xsdSource != "" {
		srcBase := xsdSource
		if idx := strings.LastIndexAny(srcBase, "/\\"); idx >= 0 {
			srcBase = srcBase[idx+1:]
		}
		fmt.Fprintf(&header, "// Code generated by xsd2go-lite %s from %s. DO NOT EDIT.\n\n", version, srcBase)
	}

	header.WriteString("package ")
	header.WriteString(pkgName)
	header.WriteString("\n\n")

	if len(usedAliases) > 0 {
		// Sort aliases for deterministic import order.
		sortedAliases := make([]string, 0, len(usedAliases))
		for a := range usedAliases {
			sortedAliases = append(sortedAliases, a)
		}
		sort.Strings(sortedAliases)
		header.WriteString("import (\n")
		for _, alias := range sortedAliases {
			fmt.Fprintf(&header, "\t%s %q\n", alias, importPaths[alias])
		}
		header.WriteString(")\n\n")
	}

	src := header.String() + structsSB.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Return unformatted with the error so caller can debug.
		return src, fmt.Errorf("go/format: %w\n--- unformatted source ---\n%s", err, src)
	}
	return string(formatted), nil
}

func writeStruct(sb *strings.Builder, ct *ComplexType, withDoc bool, aliases map[string]string, usedAliases map[string]bool) {
	sb.WriteString("type ")
	sb.WriteString(goTypeName(ct.Name))
	sb.WriteString(" struct {\n")

	for _, f := range ct.Fields {
		goType := f.GoType
		if alias, ok := aliases[f.TypeNS]; ok {
			goType = qualifyType(goType, alias)
			usedAliases[alias] = true
		}
		if withDoc && f.Doc != "" {
			writeComment(sb, f.Doc)
		}
		sb.WriteString("\t")
		sb.WriteString(f.GoName)
		sb.WriteString(" ")
		sb.WriteString(goType)
		sb.WriteString(" `xml:\"")
		sb.WriteString(f.XMLTag)
		tag := buildTagSuffix(f)
		sb.WriteString(tag)
		sb.WriteString("\"`\n")
	}

	sb.WriteString("}\n\n")
}

// writeComment emits a doc string as Go line comments inside a struct body.
func writeComment(sb *strings.Builder, doc string) {
	for _, line := range strings.Split(doc, "\n") {
		sb.WriteString("\t// ")
		sb.WriteString(strings.TrimSpace(line))
		sb.WriteString("\n")
	}
}

// buildTagSuffix returns the options part of the xml tag after the name/ns.
func buildTagSuffix(f Field) string {
	// The XMLTag already contains ",attr" or ",chardata" if applicable.
	// We just need to append ",omitempty" if needed.
	if f.Omit && !f.IsChar {
		// Don't add omitempty to chardata or slices.
		if !f.Slice {
			return ",omitempty"
		}
	}
	return ""
}
