package xsdlite

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
)

// Generate produces a Go source file string for the given types.
// withDoc controls whether XSD documentation is emitted as field comments.
// mapNS maps namespace URI → Go package import path. Types from those
// namespaces are not generated as structs (they come from the external package),
// but fields referencing them are kept and their Go type is qualified with the
// derived package alias.
// xsdSource is the input XSD file path (used in the generated-file header).
// version is the tool version string (used in the generated-file header).
func Generate(types []*ComplexType, pkgName string, skipAbstract bool, withDoc bool, mapNS map[string]string, xsdSource string, version string) (string, error) {
	// Build ns→alias and alias→pkgPath tables, checking for alias collisions.
	aliases := make(map[string]string)     // ns → alias
	importPaths := make(map[string]string) // alias → pkgPath
	aliasToNS := make(map[string]string)   // alias → first ns (collision detection)
	for ns, pkgPath := range mapNS {
		alias := deriveAlias(pkgPath)
		if prevNS, exists := aliasToNS[alias]; exists && prevNS != ns {
			return "", fmt.Errorf("alias collision: namespaces %q and %q both derive alias %q; use different package paths", prevNS, ns, alias)
		}
		aliases[ns] = alias
		importPaths[alias] = pkgPath
		aliasToNS[alias] = ns
	}

	// Sort for deterministic output.
	sort.Slice(types, func(i, j int) bool {
		return types[i].Name < types[j].Name
	})

	usedAliases := make(map[string]bool)
	var structsSB strings.Builder
	for _, ct := range types {
		if skipAbstract && ct.Abstract {
			continue
		}
		if ct.Name == "" {
			continue
		}
		writeStruct(&structsSB, ct, withDoc, aliases, usedAliases)
	}

	var header strings.Builder

	// Generated-file header (only when at least one of version/xsdSource is set).
	if version != "" || xsdSource != "" {
		srcBase := xsdSource
		if idx := strings.LastIndexAny(srcBase, "/\\"); idx >= 0 {
			srcBase = srcBase[idx+1:]
		}
		fmt.Fprintf(&header, "// Code generated by xsd2go-lite %s from %s. DO NOT EDIT.\n\n", version, srcBase)
	}

	header.WriteString("package ")
	header.WriteString(pkgName)
	header.WriteString("\n\n")

	if len(usedAliases) > 0 {
		// Sort aliases for deterministic import order.
		sortedAliases := make([]string, 0, len(usedAliases))
		for a := range usedAliases {
			sortedAliases = append(sortedAliases, a)
		}
		sort.Strings(sortedAliases)
		header.WriteString("import (\n")
		for _, alias := range sortedAliases {
			fmt.Fprintf(&header, "\t%s %q\n", alias, importPaths[alias])
		}
		header.WriteString(")\n\n")
	}

	src := header.String() + structsSB.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Return unformatted with the error so caller can debug.
		return src, fmt.Errorf("go/format: %w\n--- unformatted source ---\n%s", err, src)
	}
	return string(formatted), nil
}

func writeStruct(sb *strings.Builder, ct *ComplexType, withDoc bool, aliases map[string]string, usedAliases map[string]bool) {
	sb.WriteString("type ")
	sb.WriteString(goTypeName(ct.Name))
	sb.WriteString(" struct {\n")

	for _, f := range ct.Fields {
		goType := f.GoType
		if alias, ok := aliases[f.TypeNS]; ok {
			goType = qualifyType(goType, alias)
			usedAliases[alias] = true
		}
		if withDoc && f.Doc != "" {
			writeComment(sb, f.Doc)
		}
		sb.WriteString("\t")
		sb.WriteString(f.GoName)
		sb.WriteString(" ")
		sb.WriteString(goType)
		sb.WriteString(" `xml:\"")
		sb.WriteString(f.XMLTag)
		tag := buildTagSuffix(f)
		sb.WriteString(tag)
		sb.WriteString("\"`\n")
	}

	sb.WriteString("}\n\n")
}

// qualifyType prefixes the non-builtin type name in goType with alias.
// Handles pointer (*T → *alias.T) and slice ([]T → []alias.T) prefixes.
func qualifyType(goType, alias string) string {
	prefix := ""
	base := goType
	if strings.HasPrefix(base, "[]") {
		prefix = "[]"
		base = base[2:]
	} else if strings.HasPrefix(base, "*") {
		prefix = "*"
		base = base[1:]
	}
	if isBuiltinGoType(base) || strings.Contains(base, ".") {
		return goType
	}
	return prefix + alias + "." + base
}

// deriveAlias derives a Go import alias from a package path.
// If the last segment is "generated", uses the preceding segment stripped of
// non-Go-identifier characters (hyphens, dots, etc.) plus "gen".
// Underscores are preserved as they are valid Go identifiers.
// Examples:
//
//	"github.com/foo/gml3_1_1/generated" → "gml3_1_1gen"
//	"github.com/foo/gml3_2_1/generated" → "gml3_2_1gen"
//	"github.com/foo/mypkg"              → "mypkg"
func deriveAlias(pkgPath string) string {
	parts := strings.Split(pkgPath, "/")
	// Strip characters that are not valid Go identifier chars (keep letters, digits, underscore).
	stripInvalid := func(s string) string {
		return strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
				return r
			}
			return -1
		}, s)
	}
	last := parts[len(parts)-1]
	if last == "generated" && len(parts) >= 2 {
		return stripInvalid(parts[len(parts)-2]) + "gen"
	}
	return stripInvalid(last)
}

// xmlTagNS extracts the namespace URI from an xml struct tag value.
// Tag format: "namespace localName" or "localName,attr" etc.
func xmlTagNS(tag string) string {
	if idx := strings.Index(tag, " "); idx >= 0 {
		return tag[:idx]
	}
	return ""
}

// writeComment emits a doc string as Go line comments inside a struct body.
func writeComment(sb *strings.Builder, doc string) {
	for _, line := range strings.Split(doc, "\n") {
		sb.WriteString("\t// ")
		sb.WriteString(strings.TrimSpace(line))
		sb.WriteString("\n")
	}
}

// buildTagSuffix returns the options part of the xml tag after the name/ns.
func buildTagSuffix(f Field) string {
	// The XMLTag already contains ",attr" or ",chardata" if applicable.
	// We just need to append ",omitempty" if needed.
	if f.Omit && !f.IsChar {
		// Don't add omitempty to chardata or slices.
		if !f.Slice {
			return ",omitempty"
		}
	}
	return ""
}

// goTypeName converts an XSD type name to a Go exported type name.
func goTypeName(name string) string {
	return goName(name)
}

// goName converts a name to a Go exported identifier.
func goName(name string) string {
	if name == "" {
		return "_"
	}

	// GML 3.1.1 uses "_Xxx" for abstract substitution group heads (e.g. "_Curve", "_Surface").
	// Prefix the result with "Abstract" so the concrete member field (e.g. "Curve *CurveType")
	// can coexist without being deduped away.
	leadingUnderscore := strings.HasPrefix(name, "_")

	// Replace hyphens and dots with underscores for processing.
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, ".", "_")

	// Split by underscore and capitalize each part.
	parts := strings.Split(name, "_")
	var sb strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		sb.WriteString(string(runes))
	}

	result := sb.String()
	if result == "" {
		return "_"
	}

	// If first char is a digit, prefix with underscore.
	if unicode.IsDigit([]rune(result)[0]) {
		result = "_" + result
	}

	// Avoid Go reserved words.
	result = avoidReserved(result)

	// Apply "Abstract" prefix for "_Xxx" abstract element names.
	if leadingUnderscore {
		result = "Abstract" + result
	}

	return result
}

func avoidReserved(name string) string {
	switch name {
	case "Break", "Case", "Chan", "Const", "Continue", "Default", "Defer",
		"Else", "Fallthrough", "For", "Func", "Go", "Goto", "If", "Import",
		"Interface", "Map", "Package", "Range", "Return", "Select", "Struct",
		"Switch", "Type", "Var":
		return name + "Field"
	}
	return name
}
