package cmd

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const fileHeader = `// Code generated by cmd/epsg-gen. DO NOT EDIT.
//
// Data sourced from the EPSG Geodetic Parameter Dataset.
// Copyright © IOGP. All rights reserved. See https://epsg.org/terms-of-use.html

package core

// epsgDimTable maps EPSG code to the number of spatial dimensions defined by that CRS.
var epsgDimTable = map[int]uint{
`

// entryRe matches lines of the form:  4326: 2, // WGS 84
var entryRe = regexp.MustCompile(`^\s+(\d+):\s+(\d+),(?:\s+//\s*(.*))?$`)

// readExisting parses an existing epsg_dim_table.go and returns its entries.
// Returns os.ErrNotExist if the file does not exist.
func readExisting(path string) (map[int]crsEntry, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	entries := make(map[int]crsEntry)
	for _, line := range strings.Split(string(src), "\n") {
		m := entryRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		code, _ := strconv.Atoi(m[1])
		dim, _ := strconv.ParseUint(m[2], 10, 64)
		entries[code] = crsEntry{Code: code, Dim: uint(dim), Name: strings.TrimSpace(m[3])}
	}
	return entries, nil
}

// writeTable writes all entries sorted by EPSG code to path.
func writeTable(path string, entries map[int]crsEntry) error {
	codes := make([]int, 0, len(entries))
	for c := range entries {
		codes = append(codes, c)
	}
	sort.Ints(codes)

	var sb strings.Builder
	sb.WriteString(fileHeader)
	for _, c := range codes {
		e := entries[c]
		if e.Name != "" {
			fmt.Fprintf(&sb, "\t%d: %d, // %s\n", c, e.Dim, e.Name)
		} else {
			fmt.Fprintf(&sb, "\t%d: %d,\n", c, e.Dim)
		}
	}
	sb.WriteString("}\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}
	return os.WriteFile(path, formatted, 0644)
}
